### ISSUE TITLE
How decrypt data on backend side?

### ISSUE THREAD

**Issue by Lasoty** [memd24/Blazor.SubtleCrypto#1]
I have a situation: I'm encrypt data on frontend and send to backend (via RestAPI) and at now I trying to decrypt this data. How I can do this?

**Comment by memd24** [comment]
This library is only for Blazor aplications, you need to use it in Blazor WebAssembly or Blazor Server. It doesn't works for other proyects like a Web API,

**Comment by ekjuanrejon** [comment]
how about decrypting a payload received via api?
