### ISSUE TITLE
Platform.NotSupported Exception on Decrypt

### ISSUE THREAD

**Issue by madcoda9000** [memd24/Blazor.SubtleCrypto#2]
HI,

i am using your library in a blazor (hosted) project.

Encrypting with the following code works without any hassle:

```
var encPass = await _crypt.EncryptAsync(secret.S_Password);
string encrypted = encPass.value;
```

After that i have saved the encrypted string into a mysql database. 
When i Try to decrypt the stored value in an other component like this (where src is the value retrieved from the database):

```
var res = await _crypt.DecryptAsync<string>(src);
Console.WriteLine("Decrypted: " + res);

```
It throws a Platform.NotSupported Exception:

<img width="2064" alt="Bildschirmfoto 2022-08-09 um 14 50 44" src="https://user-images.githubusercontent.com/25504739/183651263-0ea9f14d-738b-49de-b9b7-8365254b4420.png">

I Hope someone has an idea, what the problem is...

**Comment by memd24** [comment]
hmm that's weird. Typically the 'Platform.Not Supported Exception' occurs when you try to run something that is not supported by the project. In Blazor I have seen this problem for example when you want to run SQLClient from WASM https://github.com/dotnet/SqlClient/issues/599 . 

I made a simple blazor server example for encrypt and decrypt a simplem text check if it could help
https://github.com/memd24/BlazorSubtleCryptoSample

**Comment by madcoda9000** [comment]
Hmmm, maybe its because i do not have a blazor server project? I have a blazor wasm (hosted) Application project.

![2022-08-10 11_20_46-SecPass - Microsoft Visual Studio](https://user-images.githubusercontent.com/25504739/183865352-8585f09b-7243-4810-b9a0-65ac48d50b1b.png)

**Comment by memd24** [comment]
This nuget package is compatible for Blazor Server and Blazor WASM using Net 6. In Blazor WASM this library should be used only in the Client project.
This is an simple project sample using WASM  
https://github.com/memd24/BlazorWASMEncodeSample

**Comment by madcoda9000** [comment]
Hello,

Thank you for your support. I really appreciate that.

Your TestProject worked perfectly! Nevertheless, the error kept occurring for me, although my implementation was exactly the same as in your test project.

Then I did a "dotnet clean". And suddenly it also worked in my project without an error message. So it seems to have been a cache problem somehow.

Greeting
sascha
